---
apiVersion: meta.pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-dummy
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/crossplane-contrib/function-dummy
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: A composition function that returns what you tell it to
    meta.crossplane.io/readme: |
      This composition function returns whatever you tell it to. Provide a
      YAML-serialized [`RunFunctionResponse`](https://buf.build/crossplane/crossplane/docs/main:apiextensions.fn.proto.v1beta1)
      as the function's input. The response's `desired` object will be merged
      onto any desired state that was passed to the function using
      [`proto.Merge`](https://pkg.go.dev/github.com/golang/protobuf/proto#Merge)
      semantics. See the [README](https://github.com/crossplane-contrib/function-dummy)
      for examples and documentation.
spec:
  capabilities:
  - composition
  - operation
